### ISSUE TITLE
ReferenceError: weakly-referenced object no longer exists

### ISSUE THREAD

**Issue by markusressel** [vpaliy/lru-cache#3]
Hey there, great library :+1: 

I am using your lib to cache the response data of a REST api, see [here](https://github.com/markusressel/grocy-telegram-bot/blob/master/grocy_telegram_bot/cache.py). The cache is accessed from multiple threads concurrently and I explicitly set `concurrent=True`.

However, when running a couple of calls that also involve clearing the cache, I get the following exception:
```
2020-03-03 04:39:30,969 - root - ERROR - Error in callback
Traceback (most recent call last):
  File "/home/markus/programming/PycharmProjects/grocy-telegram-bot/venv/lib/python3.8/site-packages/telegram_click/decorator.py", line 131, in wrapper
    return func(*args, **{**kw_function_args, **kwargs})
  File "<decorator-gen-10>", line 2, in _shopping_lists_callback
  File "/home/markus/programming/PycharmProjects/grocy-telegram-bot/venv/lib/python3.8/site-packages/prometheus_client/context_managers.py", line 66, in wrapped
    return func(*args, **kwargs)
  File "/home/markus/programming/PycharmProjects/grocy-telegram-bot/grocy_telegram_bot/bot.py", line 383, in _shopping_lists_callback
    shopping_list_items = self._grocy.shopping_list(True)
  File "/home/markus/programming/PycharmProjects/grocy-telegram-bot/grocy_telegram_bot/cache.py", line 61, in wrapper
    CACHE[key] = response
  File "/home/markus/programming/PycharmProjects/grocy-telegram-bot/venv/lib/python3.8/site-packages/lru/cache.py", line 306, in __setitem__
    self.add(key, value)
  File "/home/markus/programming/PycharmProjects/grocy-telegram-bot/venv/lib/python3.8/site-packages/lru/cache.py", line 39, in _lock
    return method(self, *args, **kwargs)
  File "/home/markus/programming/PycharmProjects/grocy-telegram-bot/venv/lib/python3.8/site-packages/lru/cache.py", line 332, in add
    self._cleaner_manager.add(node)
  File "/home/markus/programming/PycharmProjects/grocy-telegram-bot/venv/lib/python3.8/site-packages/lru/cache.py", line 203, in add
    self._queue.put(node)
  File "/usr/lib/python3.8/queue.py", line 149, in put
    self._put(item)
  File "/usr/lib/python3.8/queue.py", line 233, in _put
    heappush(self.queue, item)
ReferenceError: weakly-referenced object no longer exists
```

I don't really know what this is about. Any idea what I can try?
**EDIT:**
Could this be caused by the fact that I am storing the cached value in some other classes, where I try to access those values after the cache was cleared? I tried to use `copy.deepcopy()` but it didn't help. It also seems like the error is happening when assigning a new cache value, after the cache has been cleared, not when accessing data from the cache.

**Comment by markusressel** [comment]
Here is a screenshot of IntelliJ debugging, hope it helps:

![image](https://user-images.githubusercontent.com/14024504/75741718-c20ee180-5d0b-11ea-8b77-625de2de7da3.png)

**Comment by markusressel** [comment]
I have resorted to using [expiringdict](https://github.com/mailgun/expiringdict) for now, where the same use case seems to work fine.
